- alias: Nighttime Nudge
  trigger:
    platform: time
    at: "20:30:00"
  action:
    service: script.nighttime_lights

- alias: Morning Wakeup
  trigger:
    platform: time
    at: "5:31:00"
  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
    service: script.morning_wakeup
  action:
    service: scene.turn_on
    entity_id: scene.accent_on

- alias: Should be in bed
  trigger:
    platform: time
    at: "21:30:00"
  action:
    service: scene.turn_on
    entity_id: scene.accent_off
    
- alias: Watching TV
  trigger:
    platform: state
    entity_id: media_player.living_room_tv
    from: "idle"
    to: "playing"
  action:
    service: scene.turn_on
    entity_id: scene.watching_tv