- platform: bluetooth_tracker

- platform: nmap_tracker
  hosts:
  - 10.0.0.48
  - 10.0.0.147
  
- platform: life360
  accounts:
    - username: !secret life360_username
      password: !secret life360_password